// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function CancelSession():Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetPendingQuestions():Promise<main.PendingQuestionsPayload>;

export function GetSession():Promise<main.Session>;

export function GetTickets():Promise<Array<main.TicketSummary>>;

export function GetWorkDir():Promise<string>;

export function PauseSession():Promise<void>;

export function PickDirectory():Promise<string>;

export function ResetSession():Promise<void>;

export function ResumeSession():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartSession(arg1:string,arg2:string,arg3:string):Promise<main.Session>;

export function SubmitQuestionAnswers(arg1:Array<string>):Promise<void>;
