// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSession() {
  return window['go']['main']['App']['CancelSession']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentBranch(arg1) {
  return window['go']['main']['App']['GetCurrentBranch'](arg1);
}

export function GetPendingQuestions() {
  return window['go']['main']['App']['GetPendingQuestions']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function GetTickets() {
  return window['go']['main']['App']['GetTickets']();
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function PauseSession() {
  return window['go']['main']['App']['PauseSession']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function ResetSession() {
  return window['go']['main']['App']['ResetSession']();
}

export function ResumeSession() {
  return window['go']['main']['App']['ResumeSession']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSession'](arg1, arg2, arg3);
}

export function SubmitQuestionAnswers(arg1) {
  return window['go']['main']['App']['SubmitQuestionAnswers'](arg1);
}
